[project]
name = "course-scrape"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "groq>=0.36.0",
    "ipykernel>=7.1.0",
]
